version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: 'threeguys/images'
    IMAGE_TAG: 'skynet-python'
    DOCKERFILE_NAME: 'Dockerfile.sagemaker'

phases:
  pre_build:
    commands:
      - echo Retrieving AWS account id...
      - AWS_ACCOUNT_ID=$(aws --region $AWS_DEFAULT_REGION sts --endpoint-url https://sts.$AWS_DEFAULT_REGION.amazonaws.com get-caller-identity --query 'Account' --output text)
      - echo IMAGE_REPO_NAME = $IMAGE_REPO_NAME
      - echo IMAGE_TAG = $IMAGE_TAG
      - echo DOCKERFILE_NAME = $DOCKERFILE_NAME
      - echo AWS_ACCOUNT_ID = $AWS_ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION

  build:
    commands:
      # This is an ugly hack but my 
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-west-2.amazonaws.com
      - echo Docker build started on `date`
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f $DOCKERFILE_NAME .

      - echo Tagging ECR image, retrieving login...
      - $(aws ecr get-login- --no-include-email --region $AWS_DEFAULT_REGION)
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
