FROM tensorflow/tensorflow:2.1.0-gpu-py3

RUN apt update && apt-get install -y python3-pip \
         && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir praw numpy sagemaker-containers

COPY skynet/ /opt/ml/code/skynet/
COPY train_sagemaker.py /opt/ml/code/train_sagemaker.py

ENV SAGEMAKER_PROGRAM train_sagemaker.py
