FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.1.0-gpu-py36-cu101-ubuntu18.04

RUN apt update && apt-get install -y python3-pip \
         && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir praw numpy

COPY skynet/ /opt/ml/code/skynet/
COPY train_sagemaker.py /opt/ml/code/train_sagemaker.py

ENV SAGEMAKER_PROGRAM train_sagemaker.py
